### ISSUE TITLE
Broken video streams on some networks with restricitve firewalls, how to identify the exact issue?

### ISSUE THREAD

**Issue by Kerl13** [jech/galene#43] opened 2021-01-18 13:03 UTC
Hi!

I could not start a meeting today because video streams were not transmitted.
I suspect my university's network is the culprit here, it is known to block some random (useful) ports.
Unfortunately, I'm new to this kind of debugging so I'd be glad if you could give some hints how to identify the problem.

Here is some context I think might be relevant:

- it was a two people meeting
- on both ends we could watch our own video but not the other person's (hence my guess that this is firewall/network related)
- we could see each other as "connected" in the left menu and the chat was working
- that was the first time I was using Galène from my university
- I've been using Galène successfully from home for the past few weeks on the same laptop
- I know one other person who has had the same issue on eduroam (also known to block too many ports)
- Jitsi works fine on the same network

Thanks in advance if you can give me some advice how to debug this and let me know if I can do something useful for Galène on this front.
Btw, thanks for making Galène, it is great! It is certainly one of the best open source options for videoconferencing at the moment.

**Comment by jech** [comment] 2021-01-18 17:18
1. Are you running a TURN server?  If so, on what port?  (The *Eduroam Service Definition* states that port 1194 must be open for outgoing traffic).
2. Does the server print a message about the relay test shortly after startup?  What does it say?  (If it doesn't, please upgrade Galène).
3. What happen when you joint a group and type `/relay-test` in the chat window?

**Comment by Niols** [comment] 2021-01-18 17:33
Hello @jech and thank you for the answer!

I'm the administrator of the Galene server in question here.

> 1. Are you running a TURN server?  If so, on what port?  (The _Eduroam Service Definition_ states that port 1194 must be open for outgoing traffic).

At the time where this issue was posted, we were **not** running a TURN server. We are now – and galene is aware of it – on port 1194.

> 2. Does the server print a message about the relay test shortly after startup?  What does it say?  (If it doesn't, please upgrade Galène).

The server used to say:

```
$ ./galene
2021/01/18 18:23:57 Relay test failed: timeout
2021/01/18 18:23:57 Perhaps you didn't configure a TURN server?
```

but this is fixed now and it says:

```
$ ./galene
2021/01/18 18:29:49 2021-01-18 18:29:49.392328219 +0100 CET
2021/01/18 18:29:49 2021-01-18 18:29:49.39395628 +0100 CET m=+0.156357499
2021/01/18 18:29:49 Relay test successful in 150.443157ms, RTT = 1.698433ms
```

The TURN server seems to be running fine and does pass tests like https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ .

> 3. What happen when you joint a group and type `/relay-test` in the chat window?

```
Relay test in progress...
Relay test successful in 237ms, RTT 17ms
```

------

@Kerl13 @jluiselli The server's configuration has changed quite a bit since you reported your issue. Can you try again and see if the issue persists?

**Comment by jech** [comment] 2021-01-18 22:40
@Niols, thanks.  Current master has a built-in TURN server, so this should not be an issue in the future.

Please reopen (or file another issue) if the problem is still there.

**Closed by jech** 2021-01-18 22:40 UTC

**Comment by Kerl13** [comment] 2021-01-19 10:29
Thanks to both of you for your quick reactions. @Niols and I just tested the latest master with the builtin TURN server and it works like a charm. Also, I got similar numbers as above when running the `/relay-test` command.

**Comment by Niols** [comment] 2021-01-20 10:43
Hey @jech.

As @Kerl13 said, we tried the builtin TURN server (on c1b689b) on port 1194 and it works like a charm indeed. I also tried today with someone behind an Eduroam firewall and it also worked nicely. Thank you for your time and for this great software!
