### ISSUE TITLE
Admin tools

### ISSUE THREAD

**Issue by athoune** [jech/galene#24] opened 2021-01-05 09:04 UTC
Administrators need some clues while hosting galene services.
Something standard, from the outside (without joining any rooms).

## Golang's pprof

Golang can expose pprof stuff as HTTP, providing some client tools.

## Application stats

Galene already has webrtc stats for each rooms

## Prometheus endpoint

Prometheus is the de facto tool for exposing metrics.
It can be read with Prometheus and other time series collector, like [telegraf](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus).
Prometheus endpoint is human readable, with comments.

## Security

The draft use a private website, listening on localhost, authentication should be added

## UI

For now, there is no UI, just REST endpoints.

See #23

**Comment by jech** [comment] 2021-01-07 18:31
Duplicate of #23.

**Closed by jech** 2021-01-07 18:31 UTC
