### ISSUE TITLE
Galene Yunohost Update 0.6.2 Affects Group Links

### ISSUE THREAD

**Issue by ralphshinevar** [jech/galene#157] opened 2023-03-24 20:43 UTC
This update changes the link of groups on the main page to https://example.com/undefined.  Link then does not work. Please help.  

1 January 2023: Galene 0.6.2

  * Disable simulcast for screensharing; this didn't work well with many
    browsers.
  * Fix parsing of VP8 packets with degenerate headers.
  * Fix computation of group URL when running in insecure mode.
  * Add configuration option "proxyURL", which makes it easier to run
    Galene behind a reverse proxy.
  * Disable ulimit checking on BSD systems, where our code doesn't compile.

**Comment by jech** [comment] 2023-04-01 13:23
Strange, nothing changed in that code.  Could you please check if there's anything in the Javascript console?

**Comment by ralphshinevar** [comment] 2023-04-01 13:51
I was able to fix the issue by fixing the config.json file. Added my admin
password to it.

**Comment by jech** [comment] 2023-04-01 16:03
Could you please indicate how to reproduce the issue?

**Comment by ralphshinevar** [comment] 2023-04-01 16:25
Hey Juliusz,

When I did the Galene 0.6.20.6.2~ynh3 update, the main page group links
stopped working.  The link would read "
https://video.shinevar.nohost.me/undefined"  This persisted until I fixed
the config.json file by putting my password in for my admin account.

Hope this helps,

Ralph Shinevar

**Comment by jech** [comment] 2023-04-01 16:49
> This persisted until I fixed the config.json file by putting my password
> in for my admin account.

Unfortunately it does not.  I'm unable to reproduce the issue.

Can you please confirm that you are able to reproduce the issue by
removing your password?  If you can reproduce it, then please send me an
example config file that triggers the issue.  If you cannot reproduce it,
then please close this issue.

-- Juliusz

**Comment by ralphshinevar** [comment] 2023-04-01 19:36
Do not want to break the fix.

**Closed** 2023-04-01 19:35 UTC

**Comment by jech** [comment] 2023-04-12 16:07
This is the upstream Galene repository.  I do not run Yunohost, and do not have access to the Yunohost installer.

I have tried manually removing the password from the config file, and I have not been able to reproduce your bug.  If you can reproduce the bug by editing the config file, please tell me how to do it.

**Comment by ralphshinevar** [comment] 2023-04-12 16:47
Juliusz,

I am not a developer, merely a sysadm.  I did look at all of the *.js files
and none of them referenced the config.json file.

Ralph
